[package]
name = "deck"
version = "0.1.0"
authors = ["Florian Dehau <work@fdehau.com>"]
edition = "2018"

[dependencies]
pulldown-cmark = "0.2"
syntect = "3.0"
structopt = "0.2"
warp = "0.1"
futures = "0.1"
log = "0.4"
pretty_env_logger = "0.3"
minifier = "0.0.28"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
inotify = "0.7"
tokio = "0.1"
